# Generated by Django 4.2.10 on 2024-04-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trbsAppStatisticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_link', models.TextField(default='', null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('total_van', models.TextField(default='0', null=True)),
                ('total_flat', models.TextField(default='0', null=True)),
                ('total_reffer', models.TextField(default='0', null=True)),
            ],
            options={
                'db_table': 'trbs_statistic',
            },
        ),
    ]
